- name: Check if kubeconfig exists
  ansible.builtin.stat:
    path: /etc/rancher/rke2/rke2.yaml
  register: kubeconfig_check

- name: Throw error if kubeconfig doesn't exist
  ansible.builtin.fail:
    msg: "Kubeconfig not found at /etc/rancher/rke2/rke2.yaml"
  when: not kubeconfig_check.stat.exists

- name: Set kubeconfig environment variable
  ansible.builtin.set_fact:
    rancher_kubeconfig: "/etc/rancher/rke2/rke2.yaml"

- name: Create namespace for deployment
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    kubeconfig: "{{ rancher_kubeconfig }}"
    state: present

- name: Load frontend deployment config
  ansible.builtin.include_vars:
    file: deployment_fe.yaml
    name: deployment_config_fe

- name: Load backend deployment config
  ansible.builtin.include_vars:
    file: deployment_be.yaml
    name: deployment_config_be

# TODO: more roles for switching deployment strategies
- name: Make kubernetes frontend deployment
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rancher_kubeconfig }}"
    definition: "{{ deployment_config_fe }}"
  register: deployment_result_fe

- name: Make backend kubernetes deployment
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rancher_kubeconfig }}"
    definition: "{{ deployment_config_be }}"
  register: deployment_result_be

# - name: Display deployment results
#   debug:
#     var: deployment_result

- name: Load frontend service config
  ansible.builtin.include_vars:
    file: service_fe.yaml
    name: service_config_fe

- name: Load backend service config
  ansible.builtin.include_vars:
    file: service_be.yaml
    name: service_config_be

- name: Load prometheus service config
  ansible.builtin.include_vars:
    file: service_prom.yaml
    name: service_config_prom

- name: Make frontend service
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rancher_kubeconfig }}"
    definition: "{{ service_config_fe }}"

- name: Make backend service
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rancher_kubeconfig }}"
    definition: "{{ service_config_be }}"

- name: Make prometheus service
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rancher_kubeconfig }}"
    definition: "{{ service_config_prom }}"