- name: Check if kubeconfig exists
  ansible.builtin.stat:
    path: /etc/rancher/rke2/rke2.yaml
  register: kubeconfig_check

- name: Throw error if kubeconfig doesn't exist
  ansible.builtin.fail:
    msg: "Kubeconfig not found at /etc/rancher/rke2/rke2.yaml"
  when: not kubeconfig_check.stat.exists

- name: Set kubeconfig environment variable
  ansible.builtin.set_fact:
    rancher_kubeconfig: "/etc/rancher/rke2/rke2.yaml"

- name: Create namespace for deployment
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    kubeconfig: "{{ rancher_kubeconfig }}"
    state: present

- name: Load deployment config
  ansible.builtin.include_vars:
    file: deployment.yaml
    name: deployment_config

# TODO: more roles for switching deployment strategies
- name: Make kubernetes deployment
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rancher_kubeconfig }}"
    definition: "{{ deployment_config }}"
  register: deployment_result

# - name: Display deployment results
#   debug:
#     var: deployment_result

- name: Load service config
  ansible.builtin.include_vars:
    file: service.yaml
    name: service_config

- name: Make service for deployment
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rancher_kubeconfig }}"
    definition: "{{ service_config }}"
      
  register: service_result

# - name: Display service results
#   debug:
#     var: service_result