- name: Check if server has docker installed
  ansible.builtin.command: which docker
  register: docker_check
  ignore_errors: true
  changed_when: false

# TODO: automate docker install on server
- name: Throw error when docker isn't present
  ansible.builtin.fail:
    msg: "Docker is required, install it: https://docs.docker.com/engine/install/"
  when: docker_check.rc != 0

- name: Check if k8s python library is installed
  ansible.builtin.command: python3 -c "import kubernetes"
  register: k8s_lib_check
  ignore_errors: true
  changed_when: false

- name: Install kubernetes python library
  ansible.builtin.pip:
    name: kubernetes
    state: present
  when: k8s_lib_check is failed
  register: k8s_lib_install_pip
  ignore_errors: true
  become: true

- name: Install kubernetes python lib through apt
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
    update_cache: yes
  when: k8s_lib_install_pip is failed
  become: true