- name: Check if registry is running
  ansible.builtin.uri:
    url: "http://{{ hostvars[TARGET_NODE]['ansible_host'] }}:{{ nodeport_registry }}/v2/"
    method: GET
  register: registry_check
  ignore_errors: true

- name: Display registry status
  debug:
    msg: "Registry is {{ 'running' if registry_check.status == 200 else 'not accessible' }}"

- name: Tag frontend image for registry
  ansible.builtin.shell:
    cmd: "docker tag website-blog:latest {{ hostvars[TARGET_NODE]['ansible_host'] }}:{{ nodeport_registry }}/website-blog:latest"
  become: true

- name: Tag backend image for registry
  ansible.builtin.shell:
    cmd: "docker tag metrics-api:latest {{ hostvars[TARGET_NODE]['ansible_host'] }}:{{ nodeport_registry }}/metrics-api:latest"
  become: true

- name: Push frontend image to registry
  ansible.builtin.shell:
    cmd: "docker push {{ hostvars[TARGET_NODE]['ansible_host'] }}:{{ nodeport_registry }}/website-blog:latest"
  become: true
  register: push_result

- name: Push backend image to registry
  ansible.builtin.shell:
    cmd: "docker push {{ hostvars[TARGET_NODE]['ansible_host'] }}:{{ nodeport_registry }}/metrics-api:latest"
  become: true
  register: push_result

- name: Display push result
  debug:
    msg: "Image pushed successfully to {{ hostvars[TARGET_NODE]['ansible_host'] }}:{{ nodeport_registry }}/website-blog:latest"
  when: push_result.rc == 0

- name: Verify image in registry
  ansible.builtin.uri:
    url: "http://{{ hostvars[TARGET_NODE]['ansible_host'] }}:{{ nodeport_registry }}/v2/website-blog/tags/list"
    method: GET
  register: registry_tags

- name: Display available tags
  debug:
    var: registry_tags.json