kind: Service
apiVersion: v1
metadata:
  name: docker-registry
  namespace: "{{ registry_namespace }}"
  labels:
    app: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - name: http
      port: "{{ registry_port }}"
      targetPort: "{{ registry_port }}"
      nodePort: "{{ nodeport_registry }}"
