---
- name: Check prerequisites
  hosts: localhost
  become: true
  roles:
    - role: 01_prerequisites
      tags: always
  
- name: Clone repositories and install dependencies
  hosts: localhost
  become: false
  roles:
    - role: 02_clone_repos
      tags: [repositories, setup]

- name: Check server prerequisites
  hosts: "{{ TARGET_NODE }}"
  become: true
  roles: 
    - role: 04_server_prerequisites
      tags: always

- name: Build FE and BE and make docker container
  hosts: localhost
  become: true
  roles:
    - role: 03_build_server
      tags: [build, server]

# - name: Upload exported contianer to server
#   hosts: "{{ TARGET_NODE }}"
#   become: true
#   roles:
#     - role: 05_upload_to_server
#       tags: [upload, server]

- name: Retag image and push to registry
  hosts: localhost
  become: true
  roles:
    - role: 09_push_to_registry
      tags: [push]

- name: Make kubernetes deployment and service
  hosts: "{{ TARGET_NODE }}"
  become: true
  roles:
    - role: 06_deployment_service
      tags: [k8s]

- hosts: "localhost"
  tasks:
    - assert:
        that:
          - TARGET_NODE is defined
    - pause:
        prompt: |
          -------------------------------
          You are going to DELETE deployment on the "{{ TARGET_NODE }}" node.
          -------------------------------
        seconds: 300
  tags: [delete, remove, never]

- name: Remove and roll back kubernetes deployment
  hosts: "{{ TARGET_NODE }}"
  become: true
  roles:
    - role: 07_remove_deployment_service
      tags: [delete, remove, never]

- name: Run registry install task
  hosts: "{{ TARGET_NODE }}"
  become: true
  roles:
    - role: 08_install_registry
      tags: [registry, never]

- name: Make ingress
  hosts: "{{ TARGET_NODE }}"
  become: true
  roles:
    - role: 11_setup_ingress
      tags: [ingress]

- name: Setup CDN
  hosts: "{{ TARGET_NODE }}"
  become: true
  roles:
    - role: 12_setup_cdn
      tags: [cdn, never]

- name: Clean registry
  hosts: "{{ TARGET_NODE }}"
  become: true
  roles:
    - role: 20_clean_registry
      tags: [clean, never]